// <auto-generated />
using Mango.Services.ProductAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Services.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230316090605_SeedProducts")]
    partial class SeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mango.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Appetizer",
                            ImageUrl = "https://drive.google.com/file/d/1YbDtCsClmwwYeDfzVLIyhH5jih9qnB5x/view?usp=share_link",
                            Price = 15.0,
                            ProductDescription = "A fried South Asian pastry with a savoury filling, including ingredients such as spiced potatoes, onions, and peas.",
                            ProductName = "Samosa"
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Appetizer",
                            ImageUrl = "https://drive.google.com/file/d/1euCZOZbWStvcQyueSOtx8oafD2c5mlVJ/view?usp=share_link",
                            Price = 13.99,
                            ProductDescription = "An Indian dish made from chunks of paneer marinated in spices and grilled in a tandoor.",
                            ProductName = "Paneer Tikka"
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Dessert",
                            ImageUrl = "https://drive.google.com/file/d/1jylnF37jQKvXoe1rdm--dt-UjQJdEST7/view?usp=share_link",
                            Price = 10.99,
                            ProductDescription = "A pie is a baked dish which is usually made of a pastry dough casing that contains a filling of various sweet or savoury ingredients.",
                            ProductName = "Sweet Pie"
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Entree",
                            ImageUrl = "https://drive.google.com/file/d/1aV-V_5KcMB7ankZjTezNX8ncbgYq4iie/view?usp=sharing",
                            Price = 15.0,
                            ProductDescription = "Pav Bhaji is a fast food dish from Mumbai (Bombay), India, consisting of a vegetable curry (bhaji) cooked in tomato gravy and served with a soft bread roll (pav).",
                            ProductName = "Pav Bhaji"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
